### ISSUE TITLE
Loosing drug effect -> Dropped out of car

### ISSUE THREAD

**Issue by Slamdunk91** [ESX-PUBLIC/esx_drugeffects#2]
Hello,

Since few days we are experiencing a little issue :

When the drug effect is ending, and if we are riding a car or simply inside a car we are pushed out of the car no matter what when the effects ends.

Do you know what can cause this kind of issue, is it script related or not at all ?

Thank you for your help
Slam

**Comment by Ferreira312** [comment]
Try the updated version and let me know if it is fixed :)

**Comment by Slamdunk91** [comment]
Ok I will try this out, one more question

If I want to add the fact that after using a drug the character can be able to collect items twice faster, for example fishing quicker or gathering drugs 2x quicker how should I add thisnto the drug effect?

Thank you in advance and I keep you posted

Envoyé de mon iPhone

Le 21 mai 2019 à 18:37, MrLumi <notifications@github.com<mailto:notifications@github.com>> a écrit :


Try the updated version and let me know if it is fixed :)

**Comment by Ferreira312** [comment]
you need to bring the gathering fuction from the esx_drugs and add it to an effect of your sellected drug.

Ex. if you want that to be on weed effect you will add it after the line 138 where it says "SetRunSprintMultiplierForPlayer(player, 1.0)
<-here
end)"
